Repository prgrms-web-devcourse-final-project/WEB4_5_AnjolinaJelly_BE, pull requests merged in 2025-05, with the labels that each got.

#24 Feat: 공통 응답 처리 개선 (#23)
  src/main/java/com/jelly/zzirit/domain/member/controller/AuthController.java
  src/main/java/com/jelly/zzirit/domain/member/controller/InfoController.java
  src/main/java/com/jelly/zzirit/global/converter/BaseHttpsMessageConverter.java
  src/main/java/com/jelly/zzirit/global/converter/exception/NotSupportedException.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponse.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/main/java/com/jelly/zzirit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/jelly/zzirit/global/security/filter/LoginFilter.java
  src/main/java/com/jelly/zzirit/global/security/oauth2/handler/CustomOAuth2FailureHandler.java
  src/main/java/com/jelly/zzirit/global/wrapper/ResponseWrapper.java
Labels: feat

#35 Chore: Swagger 설정 추가 (#34)
  build.gradle
  src/main/java/com/jelly/zzirit/global/config/SwaggerConfig.java
Labels: chore

#38 Docs: 주문 도메인 API 문서화 작업 (#32)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/order/dto/response/OrderFetchResponse.java
  src/main/java/com/jelly/zzirit/domain/orderitem/dto/request/OrderItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/orderitem/dto/response/OrderItemFetchResponse.java
Labels: docs

#39 Docs: 관리자 상품 api 문서화 (#19)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/ImageUploadResponse.java
  src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
  src/test/java/com/jelly/zzirit/domain/adminItem/Controller/AdminItemControllerTest.java
Labels: docs

#48 Refactor: 장바구니 API 태그 내용 변경 (#43)
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartController.java
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
Labels: refactor

#57 Feat: 초기 데이터 생성
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/domain/item/repository/BrandRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TypeRepository.java
  src/main/java/com/jelly/zzirit/global/dataInit/DataInitializer.java
  src/main/java/com/jelly/zzirit/global/dataInit/SqlScriptExecutor.java
  src/main/resources/data.sql
Labels: feat

#61 Feat: 상품 카테고리 조회 (#60)
  src/main/java/com/jelly/zzirit/domain/item/controller/BrandController.java
  src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
  src/main/java/com/jelly/zzirit/domain/item/controller/TypeController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/TypeResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/BrandResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/ItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/SimpleItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/TypeResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/TypeResponses.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Type.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryTypeService.java
Labels: feat

#66 Feat: 관리자 상품 목록 조회 api 구현 (#56)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/QueryAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
  src/main/java/com/jelly/zzirit/global/dataInit/AdminAccountInitializer.java
Labels: feat

#68 Feat: 관리자 상품 등록 api 구현 (#67)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/QueryAdminItemService.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/main/java/com/jelly/zzirit/global/exception/custom/InvalidItemException.java
Labels: feat

#70 Feat: 관리자 상품 수정 api 구현 (#69)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/domain/order/repository/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
Labels: feat

#72 Feat: 관리자 상품 삭제&검색 기능 구현 (#71)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/QueryAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemRepository.java
Labels: feat

#73 Feat: 타임딜 등록 페이지 기능 구현 (#59)
  src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/TimeDealCreateItem.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/TimeDealModalItem.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealCreateResponse.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealResponseDTO.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/service/TimeDealService.java
  src/test/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealControllerTest.java
Labels: feat

#76 Chore: 엔티티 수정 (#75)
  src/main/java/com/jelly/zzirit/domain/cart/entity/Cart.java
  src/main/java/com/jelly/zzirit/domain/cart/entity/CartItem.java
  src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/ItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/SimpleItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Brand.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/ItemStatus.java
  src/main/java/com/jelly/zzirit/domain/item/entity/TypeBrand.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/TimeDealStock.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDealItem.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Order.java
  src/main/java/com/jelly/zzirit/domain/order/entity/OrderItem.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Payment.java
  src/main/java/com/jelly/zzirit/domain/order/repository/TimeDealStockRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/PostPaymentProcessor.java
Labels: chore

#78 Feat: 변경된 엔티티에 맞추어 관리자 상품 CRUD 기능 수정 (#77)
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/TypeBrand.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TypeBrandRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/TimeDealStockRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/PostPaymentProcessor.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/main/resources/data.sql
Labels: refactor

#81 Feat: 장바구니 조회 API 기능 구현 (#54)
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartController.java
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TypeBrandRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/TimeDealStockRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/PostPaymentProcessor.java
  src/main/resources/application-test.yml
Labels: feat

#84 Feat: 장바구니 상품 추가, 삭제 기능 구현 (#82)
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/request/CartItemAddRequest.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/entity/CartItem.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
Labels: feat

#88 Feat: (관리자) 상품 이미지 업로드 (#85)
  build.gradle
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/S3Service.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/global/config/S3Config.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
Labels: feat

#89 Feat: 주문 취소 및 결제 취소 기능 구현 (#62)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Order.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Payment.java
  src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/repository/PaymentRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/CommandOrderService.java
  src/main/java/com/jelly/zzirit/domain/order/service/OrderCancellationFacade.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/RefundService.java
  src/main/java/com/jelly/zzirit/global/authorization/AuthorizationService.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
Labels: feat

#91 Feat: 주문 상태 변경 스케줄러 구현 (#90)
  src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/scheduler/OrderStatusScheduler.java
  src/main/java/com/jelly/zzirit/global/config/SchedulerConfig.java
Labels: feat

#92 Feat: 타임딜 등록 기능 구현(#74)
  src/main/java/com/jelly/zzirit/domain/item/controller/TimeDealController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/timeDeal/TimeDealCreateItem.java
  src/main/java/com/jelly/zzirit/domain/item/dto/timeDeal/TimeDealModalItem.java
  src/main/java/com/jelly/zzirit/domain/item/dto/timeDeal/request/TimeDealCreateItemDetail.java
  src/main/java/com/jelly/zzirit/domain/item/dto/timeDeal/response/TimeDealCreateResponse.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDealItem.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/request/TimeDealCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/service/TimeDealService.java
  src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
  src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
  src/test/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealControllerTest.java
Labels: feat, refactor

#94 Feat: 타임딜 관리자 조회 기능 구현 (#93)
  src/main/java/com/jelly/zzirit/domain/item/controller/TimeDealController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/timeDeal/response/SearchTimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/SearchTimeDealItem.java
  src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
Labels: feat

#103 Feat: 진행중인 타임딜 조회 기능 구현 (#95)
  src/main/java/com/jelly/zzirit/domain/item/controller/TimeDealController.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/CurruntTimeDeal.java
  src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/CurruntTimeDealItem.java
  src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
Labels: feat

#106 Test: 장바구니 도메인 테스트 (#97)
  build.gradle
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
Labels: test

#105 Feat: 타임딜 상태(예정, 진행중, 종료) 자동 변경 기능 구현 (#104)
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/domain/item/scheduler/TimeDealStatusScheduler.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
  src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
  src/test/java/com/jelly/zzirit/testutil/TimeDealTestHelper.java
Labels: feat

#116 Test: 상품 이미지 업로드 테스트 (#115)
  .gitignore
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/test/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/adminItem/service/S3ServiceTest.java
Labels: fix, test

#113 Chore: 사용하지 않는 주문 생성 API 삭제 (#111)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderItemCreateRequest.java
Labels: chore

#124 Refactor: 관리자 상품 수정 DTO 생성 (#123)
  src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
  src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemUpdateRequest.java
  src/main/java/com/jelly/zzirit/domain/adminItem/service/CommandAdminItemService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
Labels: refactor

#127 Refactor: 결제 프로세스 고도화 [AOP 분산락, 매퍼]
  build.gradle
  src/main/java/com/jelly/zzirit/domain/item/entity/Brand.java
  src/main/java/com/jelly/zzirit/domain/item/entity/ItemStatus.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Type.java
  src/main/java/com/jelly/zzirit/domain/member/controller/InfoController.java
  src/main/java/com/jelly/zzirit/domain/order/controller/PaymentController.java
  src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderItemRequestDto.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Order.java
  src/main/java/com/jelly/zzirit/domain/order/mapper/OrderMapper.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/ItemStockService.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/TempOrderService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/RefundService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/TossConfirmService.java
  src/main/java/com/jelly/zzirit/global/dataInit/AdminAccountInitializer.java
  src/main/java/com/jelly/zzirit/global/dataInit/DataInitializer.java
  src/main/java/com/jelly/zzirit/global/redis/lock/AopForTransaction.java
  src/main/java/com/jelly/zzirit/global/redis/lock/CustomSpringELParser.java
  src/main/java/com/jelly/zzirit/global/redis/lock/DistributedLock.java
  src/main/java/com/jelly/zzirit/global/redis/lock/DistributedLockAspect.java
  src/main/resources/application-dev.yml
  src/test/java/com/jelly/zzirit/domain/order/controller/PaymentControllerTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/ItemStockServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/TempOrderServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/pay/TossConfirmServiceTest.java
Labels: refactor

#129 Feat: 타임딜 검색 API에서 조건 없이 전체 조회하는 기능 구현 (#121)
  src/main/java/com/jelly/zzirit/domain/item/dto/request/TimeDealSearchCondition.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryTimeDealService.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
Labels: feat

#140 Test: 상품 조회 테스트 작성 (#132)
  src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/ItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/dto/response/SimpleItemResponse.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Brand.java
  src/main/java/com/jelly/zzirit/domain/item/entity/TypeBrand.java
  src/test/java/com/jelly/zzirit/domain/admin/controller/AdminItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/BrandControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/TypeControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/BrandControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/ItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/TypeControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/BrandFixture.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/ItemFixture.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/ItemStockFixture.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/TypeBrandFixture.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/TypeFixture.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryBrandServiceTest.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryTypeServiceTest.java
  src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
Labels: test

#146 Test: 관리자 상품 컨트롤러 테스트 코드 작성(성공 케이스만) (#139)
  src/test/java/com/jelly/zzirit/domain/admin/controller/AdminItemControllerTest.java
  src/test/java/com/jelly/zzirit/global/support/TestMemberConfig.java
Labels: test

#147 Test: 장바구니 도메인 단위 테스트 (#136)
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartItemServiceTest.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartServiceTest.java
Labels: refactor, test

#149 Test: 장바구니 API 테스트 작성 (#148)
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
Labels: test

#150 Feat: 주문 전체 조회 페이징 구현 (#143)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/QueryOrderService.java
  src/main/java/com/jelly/zzirit/global/dto/PageResponse.java
Labels: feat

#156 Chore: Jacoco 테스트 제외 경로 설정 (#155)
  build.gradle
Labels: chore

#162 Refactor: 장바구니 DTO record로 변경 (#161)
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartController.java
  src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/request/CartItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartFetchResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemFetchResponse.java
  src/main/java/com/jelly/zzirit/domain/cart/entity/CartItem.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartItemServiceTest.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
Labels: refactor

#131 Fix: 타임딜 등록 테스트 실패 문제 해결 (#130)
  src/test/java/com/jelly/zzirit/domain/item/contorller/TimeDealControllerTest.java
Labels: fix

#166 Feat: 쿼리 카운터 추가 (#164)
  src/main/java/com/jelly/zzirit/global/aspect/ConnectionProxyHandler.java
  src/main/java/com/jelly/zzirit/global/aspect/QueryCountAspect.java
  src/main/java/com/jelly/zzirit/global/aspect/QueryCounter.java
  src/main/java/com/jelly/zzirit/global/config/WebMvcConfig.java
  src/main/java/com/jelly/zzirit/global/interceptor/LoggingInterceptor.java
Labels: feat

#170 Fix: 이미지 업로드 API Swagger 설정 (#169)
  src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
Labels: fix

#174 Fix: Lazy 객체 조회 제거 및 응답 생성 방식 개선
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
Labels: fix

#175 Feat: 모니터링 설정 (#172)
  build.gradle
  src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
  src/main/java/com/jelly/zzirit/global/security/filter/JwtFilter.java
  src/main/java/com/jelly/zzirit/global/wrapper/ResponseWrapper.java
  src/main/resources/application.yml
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
  src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
  src/test/resources/application.yml
  src/test/resources/truncate.sql
Labels: test

#178 Refactor: 상품 검색 Param 수정 (#177)
  src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
  src/main/java/com/jelly/zzirit/domain/item/dto/request/ItemFilterRequest.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
  src/main/java/com/jelly/zzirit/global/util/StringUtils.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
Labels: refactor

#167 Refactor: 관리자 상품 리팩토링 (#152)
  src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
  src/main/java/com/jelly/zzirit/domain/admin/service/QueryAdminService.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemRepository.java
  src/main/resources/application.yml
  src/test/java/com/jelly/zzirit/domain/admin/service/QueryAdminServiceTest.java
Labels: refactor

#176 Refactor: 주문 도메인 리팩토링 (#158)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/dto/response/OrderFetchResponse.java
  src/main/java/com/jelly/zzirit/domain/order/entity/Order.java
  src/main/java/com/jelly/zzirit/domain/order/entity/OrderStatus.java
  src/main/java/com/jelly/zzirit/domain/order/mapper/OrderMapper.java
  src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/scheduler/OrderStatusScheduler.java
  src/main/java/com/jelly/zzirit/domain/order/service/OrderCancellationFacade.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/CommandOrderService.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/OrderCancelValidator.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/OrderManager.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/QueryOrderService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/RefundService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/TossPaymentValidation.java
  src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
  src/test/java/com/jelly/zzirit/domain/order/domain/fixture/OrderFixture.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/OrderManagerTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/QueryOrderServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/TempOrderServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/pay/TossPaymentValidationTest.java
Labels: feat, refactor

#168 Refactor: 장바구니 리팩토링 (#165)
  src/main/java/com/jelly/zzirit/domain/cart/mapper/CartItemMapper.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemRepository.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartItemServiceTest.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/domain/fixture/OrderFixture.java
Labels: refactor, test

#184 Feat: 주문 전체 조회 기능에 정렬 옵션 추가 (#183)
  src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
  src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/QueryOrderService.java
  src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
Labels: feat

#180 Feat: 타임 딜 생성 시 진행 기간 중복 제한 기능 구현 (#144)
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/main/java/com/jelly/zzirit/global/exception/custom/InvalidTimeDealException.java
Labels: feat

#186 Refactor: 타임딜 도메인 리팩토링
  src/main/java/com/jelly/zzirit/domain/item/dto/response/TimeDealCreateResponse.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/TimeDealQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/item/scheduler/TimeDealStatusScheduler.java
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryTimeDealService.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
  src/main/java/com/jelly/zzirit/domain/item/util/TimeDealUtil.java
Labels: refactor

#199 Test: 주문 도메인 테스트 (#179)
  src/main/java/com/jelly/zzirit/domain/order/repository/order/OrderRepository.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/QueryOrderService.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
  src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/BrandControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/ItemControllerTest.java
  src/test/java/com/jelly/zzirit/domain/item/contorller/TypeControllerTest.java
  src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
  src/test/java/com/jelly/zzirit/domain/order/controller/pay/PaymentControllerTest.java
  src/test/java/com/jelly/zzirit/domain/order/scheduler/OrderStatusSchedulerTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/CommandOrderServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/OrderCancelValidatorTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/OrderCancellationFacadeTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/QueryOrderServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/pay/CommandRefundServiceTest.java
  src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
Labels: test

#198 Chore: 트랜잭션 어노테이션 추가
  src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
  src/test/java/com/jelly/zzirit/domain/cart/service/CartItemServiceTest.java
Labels: chore

#203 Feat: 상품 수정 API에 이미지 URL 수정 기능 추가 (#202)
  src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
  src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemUpdateRequest.java
  src/main/java/com/jelly/zzirit/domain/admin/service/CommandAdminService.java
  src/main/java/com/jelly/zzirit/domain/admin/service/CommandS3Service.java
  src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/jelly/zzirit/domain/admin/service/CommandAdminServiceTest.java
Labels: feat

#206 Refactor: 상품 조회 리팩토링 (#205)
  src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
Labels: refactor

#204 Refactor: 관리자 상품 도메인 리팩토링 (#200)
  src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
  src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemCreateRequest.java
  src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemUpdateRequest.java
  src/main/java/com/jelly/zzirit/domain/admin/dto/response/AdminItemFetchResponse.java
  src/main/java/com/jelly/zzirit/domain/admin/service/CommandAdminService.java
  src/main/java/com/jelly/zzirit/domain/admin/service/CommandS3Service.java
  src/main/java/com/jelly/zzirit/domain/admin/service/QueryAdminService.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/jelly/zzirit/domain/admin/service/QueryAdminServiceTest.java
  src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
Labels: refactor, test

#207 Refactor: 상품 조회시 타임딜 상품만 조회되는 버그
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
  src/main/java/com/jelly/zzirit/global/interceptor/LoggingInterceptor.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
Labels: fix

#212 Chore: 이미지 업로드 부하 테스트용 샘플 이미지 리소스 추가 (#211)
  src/main/resources/image/Camera.avif
  src/main/resources/image/Laptop.avif
  src/main/resources/image/Refrigerator.jpg
  src/main/resources/image/Smartphone.avif
  src/main/resources/image/TabletPC.jpg
Labels: chore

#210 Refactor: 타임딜 및 재고 관련 DB 수정사항 반영 (#208)
  src/main/java/com/jelly/zzirit/domain/item/dto/request/TimeDealSearchCondition.java
  src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
  src/main/java/com/jelly/zzirit/domain/item/entity/ItemStatus.java
  src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
  src/main/java/com/jelly/zzirit/domain/item/infra/persist/TimeDealQueryRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/stock/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/domain/item/scheduler/TimeDealStatusScheduler.java
  src/main/java/com/jelly/zzirit/domain/item/service/CommandItemService.java
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
  src/test/java/com/jelly/zzirit/domain/item/service/QueryTimeDealServiceTest.java
  src/test/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerServiceTest.java
Labels: refactor

#228 Feat: 타임딜 테스트 데이터 2만 건 삽입, 타임딜 복합 인덱스 적용, 조회시간 측정 로그 찍기 (#216)
  .github/workflows/deploy-manual.yml
  src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
  src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataGenerator.java
  src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataRunner.java
  src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
Labels: feat

#226 Feat: 타임딜 등록 시 중복 시간대 안내 메시지 기능 추가
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
  src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
  src/main/java/com/jelly/zzirit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/jelly/zzirit/global/exception/custom/InvalidCustomException.java
  src/main/java/com/jelly/zzirit/global/exception/custom/InvalidTimeDealException.java
  src/test/java/com/jelly/zzirit/domain/item/service/CommandTimeDealServiceTest.java
Labels: feat

#258 Fix: 상품 더미데이터 삽입 안 되는 이슈 해결 (#257)
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/global/dataInit/DataInitializer.java
  src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataGenerator.java
  src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataRunner.java
  src/main/resources/data.sql
Labels: fix

#229 Refactor: 보안 관련 리팩토링 및 결제 분기 처리
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/stock/ItemStockRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/stock/ItemStockRepositoryCustom.java
  src/main/java/com/jelly/zzirit/domain/item/repository/stock/ItemStockRepositoryImpl.java
  src/main/java/com/jelly/zzirit/domain/order/dto/StockChangeEvent.java
  src/main/java/com/jelly/zzirit/domain/order/mapper/OrderMapper.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/CommandStockService.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/cancel/OrderCancellationFacade.java
  src/main/java/com/jelly/zzirit/domain/order/service/order/manage/CommandOrderService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/CommandPaymentInitService.java
  src/main/java/com/jelly/zzirit/domain/order/service/pay/CommandRefundStatusService.java
  src/main/java/com/jelly/zzirit/domain/order/util/AsyncStockHistoryUploader.java
  src/main/java/com/jelly/zzirit/global/config/AsyncConfig.java
  src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
  src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
  src/main/java/com/jelly/zzirit/global/security/filter/LoginFilter.java
  src/main/java/com/jelly/zzirit/global/security/util/AccountLoginRateUtil.java
  src/main/java/com/jelly/zzirit/global/security/util/AuthConst.java
  src/test/java/com/jelly/zzirit/domain/item/domain/fixture/ItemStockFixture.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/OrderCancellationFacadeTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/order/manage/CommandStockServiceTest.java
  src/test/java/com/jelly/zzirit/domain/order/service/pay/CommandRefundStatusServiceTest.java
  src/test/java/com/jelly/zzirit/global/security/filter/LoginFilterTest.java
Labels: refactor

#259 Feat: 딜레이 큐를 이용한 타임 딜 상태 변경 로직 고도화 (#256)
  src/main/java/com/jelly/zzirit/domain/item/queue/TimeDealQueueInitializer.java
  src/main/java/com/jelly/zzirit/domain/item/queue/TimeDealTask.java
  src/main/java/com/jelly/zzirit/domain/item/queue/TimeDealTaskConsumer.java
  src/main/java/com/jelly/zzirit/domain/item/queue/TimeDealTaskExecutor.java
  src/main/java/com/jelly/zzirit/domain/item/queue/TimeDealTaskProducer.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealItemRepository.java
  src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
  src/main/java/com/jelly/zzirit/domain/item/scheduler/TimeDealStatusScheduler.java
  src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
  src/main/java/com/jelly/zzirit/global/config/DelayQueueConfig.java
  src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataGenerator.java
  src/main/java/com/jelly/zzirit/global/exception/custom/TimeDealQueueException.java
  src/main/resources/application.yml
  src/test/java/com/jelly/zzirit/domain/item/service/CommandTimeDealServiceTest.java
  src/test/resources/application.yml
Labels: feat
